# Generated by Django 5.1.7 on 2025-03-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('file_type', models.CharField(max_length=1024)),
                ('upload_timestamp', models.IntegerField(default=0)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
