# Generated by Django 5.1.7 on 2025-03-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='upload_timestamp',
            field=models.IntegerField(default=0),
        ),
    ]
